### ISSUE TITLE
$app variable does not exist

### ISSUE THREAD

**Issue by alexsobiek** [delight-im/PHP-Auth#111]
Hi,

In this snippet of code for checking roles, you use a variable called $app which does not exist and is not present anywhere else. 

```
function canEditArticle(\Delight\Auth\Auth $auth) {
    return $auth->hasAnyRole(
        \Delight\Auth\Role::MODERATOR,
        \Delight\Auth\Role::SUPER_MODERATOR,
        \Delight\Auth\Role::ADMIN,
        \Delight\Auth\Role::SUPER_ADMIN
    );
}

// ...

if (canEditArticle($app->auth())) {
    // the user can edit articles here
}

// ...

if (canEditArticle($app->auth())) {
    // ... and here
}

// ...

if (canEditArticle($app->auth())) {
    // ... and here
}
```

In addition to that, when I run the following code below, I get this error: Call to undefined method Delight\Auth\Auth::hasRole()

```
if ($auth->hasRole(\Delight\Auth\Role::SUPER_MODERATOR))  { 
    //Do something
 }
```

I've followed all of the instructions and have the register, login, logout, and verification functions working.

**Comment by ocram** [comment]
Thanks for your feedback!

The usage of `$app->auth()` instead of `$auth` for the variable that holds this library’s instance was certainly a mistake. Good catch, thank you! This has now been fixed in the README: https://github.com/delight-im/PHP-Auth/commit/cbf2b52f295263fb7eaccd6646b212ce7283d3b8

Regarding the error that you’re seeing, its message claims that the class `Auth` does not contain any method named `hasRole` – but it does. So could you please check which version of this library you are using? You can look this up in your `composer.lock` (or, less precise, but still possible, in your `composer.json`) or via the `$ composer show` command.

**Comment by alexsobiek** [comment]
I have v3.1 installed. I just tried using `$auth` and I'm still getting the same error back as far as hasRole not being a defined method. 

Thanks in advance!

**Comment by ocram** [comment]
Thanks for checking the version. That version is also the cause for your problem:

As you can see in the “Releases” section or on Packagist, `v3.1` is quite an old version from August 2016. We’re currently at `v8.0.2`. So you’d need to upgrade to get the latest features.

There’s an upgrade guide for every transition between major versions in `Migration.md`. Obviously, your upgrade path involves several such major version upgrades.
